<template>
  <main class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div v-if="error" class="rounded-2xl bg-red-50 p-4 text-red-700">{{ error }}</div>
    <div v-else-if="loading" class="h-96 animate-pulse rounded-3xl bg-slate-200" />
    <div v-else-if="product" class="grid gap-8 lg:grid-cols-[1fr_.9fr]">
      <section class="space-y-4"><div class="aspect-square overflow-hidden rounded-[2rem] bg-white shadow"><img v-if="selectedImage" :src="selectedImage" class="h-full w-full object-cover" :alt="product.name"><div v-else class="grid h-full place-items-center text-slate-400">No image</div></div><div class="grid grid-cols-5 gap-3"><button v-for="image in images" :key="image.url || image.fileId" class="aspect-square overflow-hidden rounded-2xl border" @click="selectedImage = image.url || ''"><img :src="image.url" class="h-full w-full object-cover" :alt="image.altText"></button></div></section>
      <section class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-bold uppercase text-[var(--ui-primary)]">{{ product.categoryName }}</p><h1 class="mt-2 text-4xl font-black">{{ product.name }}</h1><p class="mt-3 text-slate-500">{{ product.shortDescription }}</p><div class="mt-5 flex items-end gap-3"><strong class="text-3xl text-rose-600">{{ money(selectedSku?.salePrice || selectedSku?.price || product.salePrice || product.price) }}</strong><span v-if="selectedSku?.salePrice || product.salePrice" class="text-slate-400 line-through">{{ money(selectedSku?.price || product.price) }}</span></div>
        <div class="mt-6"><p class="mb-2 font-bold">Màu sắc</p><div class="flex flex-wrap gap-2"><button v-for="variant in variants" :key="variant.id || variant.clientId" class="rounded-full border px-4 py-2 text-sm font-bold" :class="selectedVariantKey === variantKey(variant) ? 'border-slate-950 bg-slate-950 text-white' : 'border-slate-200'" @click="selectVariant(variant)"><span v-if="variant.colorCode" class="mr-2 inline-block h-3 w-3 rounded-full" :style="{ backgroundColor: variant.colorCode }" />{{ variant.colorName || variant.name }}</button></div></div>
        <div class="mt-6"><p class="mb-2 font-bold">Size</p><div class="flex flex-wrap gap-2"><button v-for="sku in availableSkus" :key="sku.id || sku.skuCode" class="rounded-xl border px-4 py-3 font-bold disabled:opacity-40" :class="selectedSku?.id === sku.id ? 'border-slate-950 bg-slate-950 text-white' : 'border-slate-200'" :disabled="sku.stock <= 0" @click="selectedSku = sku">{{ sku.size }}</button></div><p class="mt-2 text-sm text-slate-500">Tồn kho: {{ selectedSku?.stock ?? '-' }}</p></div>
        <form class="mt-8 space-y-3 rounded-3xl bg-slate-50 p-4" @submit.prevent="submitOrder"><h2 class="text-xl font-black">Đặt hàng nhanh</h2><input v-model="form.customerName" class="w-full rounded-xl border p-3" placeholder="Họ tên *"><input v-model="form.customerPhone" class="w-full rounded-xl border p-3" placeholder="Số điện thoại *"><input v-model="form.customerEmail" class="w-full rounded-xl border p-3" placeholder="Email"><textarea v-model="form.shippingAddress" class="w-full rounded-xl border p-3" placeholder="Địa chỉ giao hàng *" /><div class="grid gap-3 sm:grid-cols-[1fr_auto]"><input v-model="form.couponCode" class="rounded-xl border p-3" placeholder="Coupon"><button type="button" class="rounded-xl border px-4 font-bold" @click="validateCoupon">Validate</button></div><textarea v-model="form.note" class="w-full rounded-xl border p-3" placeholder="Ghi chú" /><button class="w-full rounded-xl bg-slate-950 px-5 py-4 font-black text-white" :disabled="submitting">{{ submitting ? 'Đang đặt...' : 'Đặt hàng' }}</button><p v-if="notice" class="text-sm font-bold" :class="noticeType === 'error' ? 'text-red-600' : 'text-emerald-600'">{{ notice }}</p></form>
      </section>
      <section class="lg:col-span-2 rounded-[2rem] border border-slate-200 bg-white p-6"><h2 class="mb-4 text-2xl font-black">Mô tả sản phẩm</h2><EditorContent :value="product.descriptionJson" /></section>
    </div>
  </main>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import EditorContent from '@/components/storefront/EditorContent.vue'
import { productApi } from '@/modules/catalog/product/api'
import { orderApi } from '@/modules/sales/order/api'
import { couponApi } from '@/modules/promotion/coupon/api'
import { getErrorMessage, isPhone, required } from '@/modules/shared/hooks'
import { asArray, money } from '@/modules/shared/types'
import type { Product, ProductSku, ProductVariant } from '@/modules/catalog/product/types'
const route = useRoute(); const loading = ref(true); const submitting = ref(false); const error = ref(''); const notice = ref(''); const noticeType = ref<'ok' | 'error'>('ok'); const product = ref<Product | null>(null); const selectedImage = ref(''); const selectedVariantKey = ref(''); const selectedSku = ref<ProductSku | null>(null)
const form = reactive({ customerName: '', customerPhone: '', customerEmail: '', shippingAddress: '', note: '', couponCode: '', quantity: 1 })
const images = computed(() => asArray(product.value?.images)); const variants = computed(() => asArray(product.value?.variants)); const skus = computed(() => asArray(product.value?.skus))
const availableSkus = computed(() => selectedVariantKey.value ? skus.value.filter((s) => s.variantId === selectedVariantKey.value || s.variantClientId === selectedVariantKey.value) : skus.value)
function variantKey(variant: ProductVariant) { return variant.id || variant.clientId || variant.name }
function selectVariant(variant: ProductVariant) { selectedVariantKey.value = variantKey(variant); selectedSku.value = availableSkus.value[0] || null; selectedImage.value = variant.imageUrl || selectedImage.value }
function validateForm() { return required(selectedSku.value?.id, 'SKU') || required(form.customerName, 'Họ tên') || required(form.customerPhone, 'Số điện thoại') || isPhone(form.customerPhone) || required(form.shippingAddress, 'Địa chỉ') }
async function validateCoupon() { if (!form.couponCode || !selectedSku.value) return; try { const data = await couponApi.validate({ code: form.couponCode, subtotalAmount: (selectedSku.value.salePrice || selectedSku.value.price) * form.quantity }); noticeType.value = data.valid ? 'ok' : 'error'; notice.value = data.message || (data.valid ? `Coupon hợp lệ, giảm ${money(data.discountAmount)}` : 'Coupon không hợp lệ') } catch (err) { noticeType.value = 'error'; notice.value = getErrorMessage(err) } }
async function submitOrder() { const msg = validateForm(); if (msg) { noticeType.value = 'error'; notice.value = msg; return } submitting.value = true; try { await orderApi.create({ customerName: form.customerName, customerPhone: form.customerPhone, customerEmail: form.customerEmail || undefined, shippingAddress: form.shippingAddress, note: form.note || undefined, couponCode: form.couponCode || undefined, paymentMethod: 'COD', shippingMethod: 'STANDARD', shippingFee: 0, items: [{ skuId: selectedSku.value?.id || '', quantity: form.quantity }] }); noticeType.value = 'ok'; notice.value = 'Đặt hàng thành công. Shop sẽ liên hệ xác nhận.' } catch (err) { noticeType.value = 'error'; notice.value = getErrorMessage(err) } finally { submitting.value = false } }
onMounted(async () => { try { product.value = await productApi.detail(String(route.params.slug)); selectedImage.value = images.value[0]?.url || ''; if (variants.value[0]) selectVariant(variants.value[0]); else selectedSku.value = skus.value[0] || null } catch (err) { error.value = getErrorMessage(err) } finally { loading.value = false } })
</script>
